name: release

on:
  push:
      tags:
        - m[0-9]+.*

jobs:
  create-release:
     name: Create TcpGateway release
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
        with:
           persist-credentials: false
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: "CHANGELOG.md"
          title: "TcpGateway $version"
          branch: main
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
