name: release

on:
  push:
      tags:
        - v[0-9]+.*

jobs:
  create-release:
     name: Create TcpGateway release
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
        with:
           persist-credentials: false
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: "CHANGELOG.md"
          title: "TcpGateway $version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-bins:
    name: "Upload release binaries"
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            features: unity
            ver: pb
#          - target: x86_64-unknown-linux-gnu
#            os: ubuntu-18.04
#            features: unity
#            ver: pb
          - target: x86_64-apple-darwin
            os: macos-latest
            features: unity
            ver: pb
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            features: unity
            ver: pb
            
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            ver: pkg
#          - target: x86_64-unknown-linux-gnu
#            os: ubuntu-18.04
#            ver: pkg
          - target: x86_64-apple-darwin
            os: macos-latest
            ver: pkg
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            ver: pkg
            
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            features: unity
            ver: pb
#          - target: aarch64-unknown-linux-gnu
#            os: ubuntu-18.04
#            features: unity
#            ver: pb
          - target: aarch64-apple-darwin
            os: macos-latest
            features: unity
            ver: pb
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            features: unity
            ver: pb
            
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            ver: pkg
#          - target: aarch64-unknown-linux-gnu
#            os: ubuntu-18.04
#            ver: pkg
          - target: aarch64-apple-darwin
            os: macos-latest
            ver: pkg
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            ver: pkg
            
            
            
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: tcpgateway
          target: ${{ matrix.target }}
          features: ${{ matrix.features || '' }}
          archive: $bin-${{ matrix.ver }}-$target-${{ matrix.os }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
